### PR TITLE
Add documentation for initial endpoints

### PR DESCRIPTION
**Pull request by jieyouxu**
Docs for initial endpoints are added:

- `GET /posts?offset={o}&limit={n}` for obtaining a feed starting at post id `o` with `n` posts per page.
- `GET /posts/{id}` for obtaining a post with given `id`.
- `GET /images/{id}/{timestamp}` for obtaining an uploaded image with file name `{id}-{timestamp}.{ext}`.

### CODE REVIEW

**Comment by jieyouxu** [comment]
You can use the `Preview` hook to preview the current docs.

**Review by henryzt — DISMISSED** [review]

**Comment by henryzt** [comment]
However, most likely we will probably not use our own image server?

**Comment by jieyouxu** [comment]
Sure. What *are* we using? In short, how should `image` resources be identified?

**Comment by magetron** [comment]
firebase?

**Comment by henryzt** [comment]
We can use the existing method, BaaS upload. Which integrates well with WeChat. Which will return the permanent URL of the file, we can store only the URL on our server, which simplifies a whole lot, see [here](https://doc.minapp.com/js-sdk/file/file.html).

**Comment by magetron** [comment]
Also, quick question why GPL?

**Comment by jieyouxu** [comment]
GPL-3.0 was picked because other repos were using GPL?

**Comment by magetron** [comment]
Is it because we are using other GPLv3 libraries (so we have to use GPL)? or its because other repos in this org is using GPL?

**Comment by magetron** [comment]
I would say Apache would be sufficient and im not a super fan of GPL

**Comment by jieyouxu** [comment]
We could change all of them to Apache 2.0.

**Comment by magetron** [comment]
That's not a huge problem. Since that requires significant amount of redundant work, how about let's stick with GPL first and see if we want to change it after release?

**Comment by jieyouxu** [comment]
Yeah we can change the license prior to major release.

**Comment by magetron** [comment]
Maybe we don't since we are super open source ethusiast! so everyone else using this repo as a template shall be open source as well.

**Review by magetron — APPROVED** [review]
Approved

**Pull request merged**
